#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)

fun() {   
    printf "The subdomain %s is a " "$2"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
    printf " record and points to "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
    echo ""
}

if [[ -z $2 ]];
then
    for i in "www" "lb-01" "web-01" "web-02"
    do
        fun "$1" "$i"
    done
else
    fun "$1" "$2"
fi
