#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)

domains=( "www" "lb-01" "web-01" "web-02" )

fun() {
    subdomain=$1
    domain=$2
   
    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 \
	| awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [[ $# -eq 1 ]];
then
    domain="$1"
    for i in "${domains[@]}"
    do
        fun "$i" "$domain"
    done
elif [[ $# -eq 2 ]];
then
    domain=$1
    subdomain=$2
    fun "$subdomain" "$domain"
fi
