#!/usr/bin/env bash
# onfigure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt -y install haproxy=2.4\*
sudo apt update && sudo apt upgrade -y
DOMAIN_NAME='eyasuc.tech'
HAPROXY_CFG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_EN_FILE='/etc/default/haproxy'
haproxy_enable=\
"
ENABLED=1
# Change the config file location if needed
CONFIG='/etc/haproxy/haproxy.cfg'
"
echo "$haproxy_enable" >> $HAPROXY_EN_FILE
haproxy_config=\
"
#--{$DOMAIN_NAME}-params-begin--
frontend {$DOMAIN_NAME}_front
        bind :80
	mode http
        default_backend nginx_server
        option forwardfor

backend {$DOMAIN_NAME}_server
        balance roundrobin
        server 114870-web-01 52.91.136.103:80 check
        server 114870-web-02 18.235.248.251:80 check
#--{$DOMAIN_NAME}-params-end--
"
echo "$haproxy_config" >> $HAPROXY_CFG_FILE
sudo service haproxy restart
