#!/usr/bin/env bash

sudo apt -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt -y install haproxy
haproxy_config=\
"
frontend nginx_front
        bind *:80
        default_backend nginx_server
        option forwardfor

backend nginx_server
        balance roundrobin
        server web-01 52.91.871.103:80 check
        server web-02 18.400.248.251:80 check
"
echo "$haproxy_config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
