#!/usr/bin/env bash
# Write a Bash script that displays:
#    To infinity and beyond indefinitely
#    With a sleep 2 in between each iteration
#    I am invincible!!! when receiving a SIGTERM signal

while true ; do
	sleep 2
	echo "To infinity and beyond"
	trap "echo I am invincible!!!" SIGTERM
done
