#!/usr/bin/env bash

for fb in {1..100}
do
	if [[ $(( $fb % 3 )) -eq 0 && $(( $fb % 5)) -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $(( $fb % 3)) -eq 0 ]]
	then
		echo "Fizz"
	elif [[ $(( $fb % 5 )) -eq 0 ]]
	then
		echo "Bizz"
	else
		echo "$fb"
	fi
	((fb++))
done
