#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20 and

foo=1
while [[ $foo -le 20 ]];
do
	echo "$foo"
	case $foo in
		4)
		echo "bad luck from China"
		  ;;
		9)
		echo "bad luck from Japan"
		  ;;
		17)
		  echo "bad luck from Italy"
		  ;;
		*)
		  ;;
	esac
	((foo++))
done
