#!/usr/bin/env bash

SCHOOL=school

if [[ -f "${SCHOOL}" || -d "${SCHOOL}" ]]
then
	echo "${SCHOOL} file exists"
	if [[ -s "${SCHOOL}" ]]
	then
		echo "${SCHOOL} file is not empty"
	else
		echo "${SCHOOL} file is empty"
	fi
	if [[ ! -d "${SCHOOL}" ]]
	then
		echo "school is a regular file"
	fi
else
	echo "${SCHOOL} file does not exist"
fi
