#!/usr/bin/env bash
#   before running the script, localhost resolves 
#   to 127.0.0.1 and facebook.com resolves to 157.240.11.35
#   after running the script, localhost resolves 
#   to 127.0.0.2 and facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
