#!/usr/bin/env bash
# run run on the container and to return a page containing \
# Hello Holberton when querying the root of it

echo "ServerName localhost" >> /etc/apache2.conf
sudo service apache2 start
